services: 

  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - ./src/db/init.sql:/database/application/init.sql
    command: --init-file /database/application/init.sql 
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

  server:
    build: ./src/
    ports:
      - "80:80"
    volumes:
      - ./src/php/:/var/www/html
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db