services: 

  db:
    image: mysql:5.7
    container_name: MYSQL
    hostname: MYSQL
    ports:
      - "8806:3306"
    volumes:
      - ./db/init.sql:/database/application/init.sql
    command: --init-file /database/application/init.sql 
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

  server:
    build: ./src/
    volumes:
      - ./src:/var/www/html
      - ./cfg/apache2.conf:/etc/apache2/apache2.conf
    links:
      - db

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:433"
    volumes:
      - ./src:/var/www/html
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db